version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/pms-service-3799v1:3"
        LoadBalancerInfo:
          ContainerName: "3-pensioner-detail-service"
          ContainerPort: "8100"
        PlatformVersion: "LATEST"
