version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
    - cd authorization-service
    - mvn install
    - echo Logging in to Amazon ECR...
    - aws --version
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
    - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
    - IMAGE_URI=${REPOSITORY_URI}:${TAG}
  build:
    commands:
    - echo Build started on `date`
    - echo $IMAGE_URI
    - docker login -u sabthosh3799 -p dockerhub@123
    - docker build -t authorization-service .
    - docker tag authorization-service $REPOSITORY_URI:authorization-service
  post_build:
    commands:
    - printenv
    - echo Build completed on `date`
    - echo $(docker images)
    - echo Pushing docker image
    - docker push $REPOSITORY_URI:authorization-service
    - echo push completed
    - printf '[{"name":"2-auth-service","imageUri":"%s"}]' $REPOSITORY_URI:authorization-service > taskdefinition.json
artifacts:
  files:
  - authorization-service/taskdefinition.json
